version: '2.1'

services:
  flask-mega-tutorial:
    image: flask-mega-tutorial
    environment:
      - FLASK_APP=microblog.py
      - SECRET_KEY=you-will-never-guess-env
    build: .
    ports:
      - "5000:5000"
    volumes: 
      - .:/app